services:
  - type: web
    name: khilafa-campaigns
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT islamic_history_app:app
